pipeline {

    agent any
 
    stages {

        stage('Checkout') {

            steps {

                checkout scm

            }

        }
 
        stage('Build') {

            steps {

                echo 'Compiling Java project...'

                sh './mvnw clean compile'

            }

        }

    }

}
 
